In [1]:
#! pip install -r requirements.txt

In [2]:
#add par to source

import sys

sys.path.append('..')

## Components

### Data

#### Prices

##### live price

In [3]:
from tradepilot.data import MarketData

dataapi = MarketData()
# live data
dataapi.get_live_price("AAPL")

         AAPL
price  227.63

In [4]:
from tradepilot.data import MarketData

dataapi = MarketData()
# live data
dataapi.get_live_price(["AAPL", "MSFT", "GOOGL"])

         AAPL    MSFT   GOOGL
price
0      227.63  409.75  185.34

##### Historic Price Data

In [5]:
from tradepilot.data import MarketData

dataapi = MarketData()
dataapi.get_historical_data("AAPL", "2025-01-01", "2025-01-10")

                                 AAPL
Date
2025-01-02 00:00:00-05:00  243.850006
2025-01-03 00:00:00-05:00  243.360001
2025-01-06 00:00:00-05:00  245.000000
2025-01-07 00:00:00-05:00  242.210007
2025-01-08 00:00:00-05:00  242.699997

In [6]:
# multiple tickers
from tradepilot.data import MarketData

dataapi = MarketData()
dataapi.get_historical_data(["AAPL", "MSFT"], "2025-01-01", "2025-01-10")

                                 AAPL        MSFT
Date
2025-01-02 00:00:00-05:00  243.850006  418.579987
2025-01-03 00:00:00-05:00  243.360001  423.350006
2025-01-06 00:00:00-05:00  245.000000  427.850006
2025-01-07 00:00:00-05:00  242.210007  422.369995
2025-01-08 00:00:00-05:00  242.699997  424.559998

### Metrics

#### Momentum

In [7]:
from tradepilot.metrics import momentum
from tradepilot.data import MarketData
dataapi = MarketData()
prices = dataapi.get_historical_data("AAPL", "2025-01-01", "2025-01-10")
# periods to calculate momentum
# 5 days
momentum(prices, 5)

AAPL   -1.150009
dtype: float64

#### get_returns

#### Annualized Returns

#### Sharpe Ratio

#### max_drawdown

### Ranking

#### Latest Momentum

In [8]:
from tradepilot.ranking import momentum_ranking

dataapi = MarketData()
timeseries = dataapi.get_historical_data(["AAPL", "TSLA"], "2025-01-01", "2025-01-10")

# 3 periods momentum
t = 3
momentum_ranking(timeseries, t)

Index(['AAPL', 'TSLA'], dtype='object')

#### Random Ranking

In [9]:
from tradepilot.ranking import random_ranking

dataapi = MarketData()
timeseries = dataapi.get_historical_data("AAPL", "2025-01-01", "2025-01-10")

seed = 42
random_ranking(timeseries, seed)

AAPL    0.37454
dtype: float64

## Simulation

In [10]:
# examples/example_backtest.py
from tradepilot.backtest import Backtest
from tradepilot.data import MarketData
from strategies.momentum import momentum_strategy

# Retrieve historical data for an asset (e.g., AAPL)
market_data = MarketData()
# For demonstration, we use a single asset; in real applications, use a DataFrame of multiple assets.
universe = market_data.get_historical_data("AAPL", "2025-01-01", "2025-01-31")

# Set up the backtest with the momentum strategy
backtest = Backtest(universe, momentum_strategy, initial_capital=10000, risk_free=0.02)
backtest.run(start="2025-01-01", end="2025-01-31")
results = backtest.evaluate()

print("Backtest Metrics:")
for key, value in results.items():
    print(f"{key}: {value}")

Running backtest from 2025-01-01 to 2025-01-31...
Backtest results:
Series([], dtype: float64)
Returns:
Series([], dtype: float64)

ZeroDivisionError: division by zero

# Trading

In [ ]:
# examples/example_live_trading.py
from tradepilot.trader import TPT
from tradepilot.broker import BrokerAPI
from tradepilot.data import MarketData
from strategies.momentum import momentum_strategy

# Retrieve recent data for an asset (e.g., AAPL)
market_data = MarketData()
universe = market_data.get_historical_data("AAPL", "2023-01-01", "2024-01-01")

# Set up and execute live trading (ensure you have proper API credentials and a paper trading account)
trader = TPT(broker_api="alpaca", universe=universe, strategy=momentum_strategy,
              capital=10000, risk_free=0.02)
trader.run()